### PR TITLE
added loading screen

### PR DESCRIPTION
**Pull request by mohammed-shakir**

### CODE REVIEW

**Comment by syko240** [comment]
> I have a formater plugin thats why it looks like i added alot of lines but its not that much extra code that was added, sorry for that :/

that is why you stage lil bro

**Comment by mohammed-shakir** [comment]
wanna go lil bro?

**Comment by syko240** [comment]
> wanna go lil bro?

its a lot easier to review that way, you are on your own here buddy, I aint got time for this.

**Comment by mohammed-shakir** [comment]
Lil bro just admit that i am better than you, no shame in that lil bro

**Review by syko240 — APPROVED** [review]
LGTM! 
but next time, stage

dont make me angy

**Comment by mohammed-shakir** [comment]
image

**Review by sanlju — APPROVED** [review]
LGTM! :)

**Pull request merged**
