### PR TITLE
Added compass button that resets camera position

### PR DESCRIPTION
**Pull request by mohammed-shakir**

### CODE REVIEW

**Comment by sanlju** [comment]
Looks good! Just some thoughts: 
* Now if you're zoomed in on a place and press the compass, the camera will zoom out and reset. Would it be better to just reset, and remain in the same zoomed in state?
* The compass icon is in the same corner as the popup window for the satellites. Currently it works, but just a heads up so the icon won't cover any information when real satellite data is used.

**Comment by mohammed-shakir** [comment]
Yeah those are good points, will change that :)

**Review by Limeiz — COMMENTED** [review]
I agree with Sandra's two points, otherwise I think it looks good!

**Comment by RyuTribal** [comment]
Dunno if we need this anymore, since it will be a hassle making it work when a satellite is selected unless we also make the button remove the selection. But at thay point I think the compass button is overstepping it's boundries

**Pull request closed without merging**
