### PR TITLE
added a view gizmo

### PR DESCRIPTION
**Pull request by RyuTribal**

### CODE REVIEW

**Review by Limeiz — COMMENTED** [review]
Would be nice to be able to click on a certain axis and realign it that way, especially if we're sort of replacing the compass with this? Would also be nice to be able to grab the view-thing and navigate around by rotating that.

**Comment by RyuTribal** [comment]
> Would be nice to be able to click on a certain axis and realign it that way, especially if we're sort of replacing the compass with this? Would also be nice to be able to grab the view-thing and navigate around by rotating that.

Yeah we have that already, the problem is you cant ever get perfect alignment back since you can only know which axis to rotate to from a give position, meaning if you are upside down, you will go to that axis still upside down. Couple that with gimbal lock issues since we use the track ball camera (no lock at 90 degrees) and we get quite a few issues. We could still look into it for sure

**Comment by RyuTribal** [comment]
I just dont knwo if we will be forced to basically recreate the orbital camera for that

**Review by mohammed-shakir — APPROVED** [review]
LGTM!

**Pull request merged**
