### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by mohammed-shakir**
Added:
- 404 error page
- scrollable tabs
- seperated community/support and donations to their own tab
- added copy right

### CODE REVIEW

**Comment by Limeiz** [comment]
Ooh nice! just making sure, är discord inviten på sidan en sån som inte går ut?

**Comment by mohammed-shakir** [comment]
> Ooh nice! just making sure, är discord inviten på sidan en sån som inte går ut?

yes it never expires

**Comment by Limeiz** [comment]
Maybe the copyright at bottom of every tab could be a bit smaller? Especially on mobile it takes up some space

**Comment by sanlju** [comment]
Looks good! But I´m not sure about the donation having its own tab. I think it can be in the community section or something. Because now it really focuses on the donation, especially with the red heart. Also the copyright bar is kinda big, so might make it a bit smaller?

**Review by Limeiz — COMMENTED** [review]
I think it looks good! Especially the 404 page, love it :) One thing I noticed is that when using the resizer and making the tab smaller, the scroll-thingy doesn't appear, unless you close and open the menu again. Otherwise I think everything loooks good :)

**Comment by mohammed-shakir** [comment]
> Looks good! But I´m not sure about the donation having its own tab. I think it can be in the community section or something. Because now it really focuses on the donation, especially with the red heart. Also the copyright bar is kinda big, so might make it a bit smaller?

Should we have only the heart or only the chat bubble thing in that case?

**Comment by sanlju** [comment]
Another thing with the resizer, when the window is very big, the icons are centered like this. Should remain on the left side I think?

Skärmavbild 2024-12-22 kl  17 58 25

**Comment by mohammed-shakir** [comment]
> Another thing with the resizer, when the window is very big, the icons are centered like this. Should remain on the left side I think?
> 
> Skärmavbild 2024-12-22 kl 17 58 25

ohh shit, didnt see that, will fix :)

**Comment by mohammed-shakir** [comment]
@Limeiz i cant make the resizer smaller than what already fit in the icons, as in i cant get it smaller than this:
image

**Comment by sanlju** [comment]
> > Looks good! But I´m not sure about the donation having its own tab. I think it can be in the community section or something. Because now it really focuses on the donation, especially with the red heart. Also the copyright bar is kinda big, so might make it a bit smaller?
> 
> Should we have only the heart or only the chat bubble thing in that case?

Hmm, not sure. The heart could work as the community tab icon, it would be cute, but it's not as clear as the bubble thing I guess. I just don't think we need 2 tabs for community and donation, but that's just my opinion:)

**Comment by mohammed-shakir** [comment]
> > > Looks good! But I´m not sure about the donation having its own tab. I think it can be in the community section or something. Because now it really focuses on the donation, especially with the red heart. Also the copyright bar is kinda big, so might make it a bit smaller?
> > 
> > 
> > Should we have only the heart or only the chat bubble thing in that case?
> 
> Hmm, not sure. The heart could work as the community tab icon, it would be cute, but it's not as clear as the bubble thing I guess. I just don't think we need 2 tabs for community and donation, but that's just my opinion:)

ok then i will keep the heart, it looks better

**Comment by mohammed-shakir** [comment]
Ok i fixed the issues :)

**Comment by sanlju** [comment]
> Ok i fixed the issues :)

Niiice!! Works great! But, I think the donation section should be under join our community

**Comment by mohammed-shakir** [comment]
> > Ok i fixed the issues :)
> 
> Niiice!! Works great!:) But, I think the donation section should be under join our community

Fixed :)

**Review by SuadHus — APPROVED** [review]
LGTM!

**Pull request merged**
