### PR TITLE
Orbitline now works as before

### PR DESCRIPTION
**Pull request by Limeiz**
Orbitline now works with rewrite #33 

Can move code in orbit.js, wasn't sure where to put it

### CODE REVIEW

**Comment by Limeiz** [comment]
maybe it's a better idea to move the other way, i'll change that

**Review by mohammed-shakir — APPROVED** [review]
LGTM!

**Review by sanlju — COMMENTED** [review]
Looks good :)

**Comment by RyuTribal** [comment]
Looks great! The only issue that I found is as you mentioned that certain orbit code is in scene instead. You can just grab the exported earth object into your orbit class and use it there.

Great use of the new event system btw!

Changes needed:
Move the orbit code to scene
Remove the big console.logs that you are doing. Usually lets try to keep logging in main to a minimum unless absolutely needed. So when you are done programming, please remove your logs if they are not needed. Especially ones where alot of data is dumped

**Pull request merged**
